### ISSUE TITLE
NullPointerException in io.github.lxgaming.discordbot.listeners.BotListener.onReady

### ISSUE THREAD

**Issue by BakermanLP** [LXGaming/DiscordBot#11]
Hello,

I don't know, if this is a configuration error or a plugin error. Here are some informations about my environment:
- HexagonMC/BungeeCord Release 123
- Loaded Plugins
  - DiscordBotBC-0.8.0-jar-with-dependencies.jar
  - ProtocolSupportBungee.jar
  - SpongePls.jar
- Behind the BungeeCord there are 2 Forge server

Configuration: "plugins/DiscordBotBC/config.yml":
```
DiscordBot:
  Credentials:
    BotToken: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    Guild: 6b3722f6-205a-42f0-9bcb-79305d7e28f8
  TextChannels:
    Bot: '253588498907529217'
    InGame: '253588498907529217'
  Messages:
    Locale: en
    CommandPrefix: '!'
    ConsoleOutput: true
    ConnectionMessage: true
    SendInGame: true
    SendDiscord: true
    ForceChat: false
  Listeners:
    MainBot: true
    UserAvatarUpdate: false
    UserGameUpdate: false
    UserNameUpdate: false
    UserOnlineStatusUpdate: false
    VoiceServerDeaf: false
    VoiceServerMute: false
  Events:
    PlayerChat: true
    PlayerJoin: true
    PlayerQuit: true
```

Error message:
http://pastebin.com/ZZg22ZV7

I've read about EssentialsChat plugin. Do I need this? Is this available for BungeeCord or is this a bukkit plugin?
