### ISSUE TITLE
Cross server chat

### ISSUE THREAD

**Issue by BakermanLP** [LXGaming/DiscordBot#12]
Hello,
is it possible to use this plugin as a cross server chat tool ? I use the Bungeecord plugin of this ( DiscordBotBC-0.8.0-jar-with-dependencies.jar ). We want cross server chat without the hassle of typing some extra commands. Communication Discord <-> Minecraft is working well.

The database is nearly empty ( empty database json tag ). The message file is untouched, no other config files are there.

Here is our config. 

```
DiscordBot:
  Credentials:
    BotToken: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    Guild: 'xxxxxxxxxx'
  TextChannels:
    Bot: 'xxxxxxxxx'
    InGame: 'xxxxxx'
  Messages:
    Locale: en
    CommandPrefix: '!'
    ConsoleOutput: true
    ConnectionMessage: true
    SendInGame: true
    SendDiscord: true
    ForceChat: true
  Listeners:
    MainBot: true
    UserAvatarUpdate: false
    UserGameUpdate: false
    UserNameUpdate: false
    UserOnlineStatusUpdate: false
    VoiceServerDeaf: false
    VoiceServerMute: false
  Events:
    PlayerChat: true
    PlayerJoin: false
    PlayerQuit: false
```
