### ISSUE TITLE
minecraft > discord doesn't work, discord > minecraft disconnects everyone

### ISSUE THREAD

**Issue by comfysquirrel** [LXGaming/DiscordBot#14]
Running:
- DiscordBot `build 18`
- BungeeCord `git:BungeeCord-Bootstrap:1.11-SNAPSHOT:806a6df:1231`
- FreeBungeeChat `2.4-SNAPSHOT` (the chat log in console is from this, I tested without this plugin and the same DiscordBot errors occur)

When someone types in chat it has an error and doesn't show up in discord.
```
19:05:15 [SEVERE] [DiscordBot] Unable to send message as format was blank or null!
19:05:15 [SEVERE] Exception in thread "Thread-35"
19:05:15 [SEVERE] java.lang.IllegalArgumentException: Provided text for message may not be null
19:05:15 [SEVERE]       at org.apache.http.util.Args.notEmpty(Args.java:61)
19:05:15 [SEVERE]       at net.dv8tion.jda.core.entities.MessageChannel.sendMessage(MessageChannel.java:182)
19:05:15 [SEVERE]       at io.github.lxgaming.discordbot.util.MessageSender.sendMessageDiscord(MessageSender.java:56)
19:05:15 [SEVERE]       at io.github.lxgaming.discordbot.util.MessageSender$1.run(MessageSender.java:37)
19:05:15 [SEVERE]       at java.lang.Thread.run(Thread.java:745)
19:05:15 [INFO] [Chat] ArcticDesigns: that's what it looked like
```
When someone types in discord it disconnects everyone.
```
19:05:26 [SEVERE] [DiscordBot] Unable to send message as format was blank or null!
19:05:26 [INFO] [DiscordBot] Jon - null
19:05:26 [INFO] [ArcticDesigns] -> UpstreamBridge has disconnected
```
![2017-05-01_12 08 12](https://cloud.githubusercontent.com/assets/6022168/25590878/07ab833c-2e67-11e7-9302-45f96f7df52c.png)

### channels.yml:
```
DiscordBot:
  Guild:
    Id: 'xxxxxxxxxxxxxxxxxx'
  Channels:
    Global:
      Command: 'null'
      Channel: 'xxxxxxxxxxxxxxxxxx (same as guild id)'
      ChatColor: true
      Permission: '*'
```

### config.yml:
```
DiscordBot:
  Credentials:
    # Information on how to get a Token below
    # https://www.spigotmc.org/resources/discordbot-bungeecord-edition.19347/update?update=85962
    Token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  Redis:
    Enabled: false
  Messages:
    # Prefix is what invokes a command eg !help
    CommandPrefix: '!'
    # Turn off DiscordBot Connected messages.
    ConnectionMessage: false
    # NOTE: In the messages.yml setting messages to 'null' will allow you to stop specific events sending messages
    # Should Messages be sent to Minecraft/Discord?
    SendDiscord: true
    SendMinecraft: true
    SendConsole: true
    # Set this to true if you want global chat messages to be sent to discord regardless of other chat plugins
    ForceChat: true
  Listeners:
    # Disable Discord based commands.
    AllowCommands: true
    # Discord Events
    # When a user changes there Avatar/Game/Name or they become Online/Away/DoNotDisturb/Offline/Deafened/Muted should$
    UserAvatarUpdate: false
    UserGameUpdate: false
    UserNameUpdate: true
    UserOnlineStatusUpdate: false
    VoiceDeafen: false
    VoiceMute: false
  Events:
    # Minecraft Events
    # Enable/Disable Chat/Join/Quit Messages
    PlayerChat: true
    PlayerJoin: true
    PlayerDeath: true
    PlayerQuit: true
```

### messages.yml:
```
DiscordBot:
  Ready:
    MinecraftFormat: '&6[&9Discord&6] &2Connected!'
    DiscordFormat: '``Time:`` **%time%** ``Discord`` **Connected!**'
  UserAvatarUpdate:
    MinecraftFormat: '&6[&9Discord&6] &f%name%: New Avatar - %message%'
    DiscordFormat: '``Time:`` **%time%** ``User:`` **%name%** ``New Avatar:`` **%message%**'
  UserGameUpdate:
    MinecraftFormat: '&6[&9Discord&6] &f%name%: Game - %message%'
    DiscordFormat: '``Time:`` **%time%** ``User:`` **%name%** ``Game:`` **%message%**'
  UserNameUpdate:
    MinecraftFormat: '&6[&9Discord&6] &f%name%: Name - %message%'
    DiscordFormat: '``Time:`` **%time%** ``User:`` **%name%** ``New name:`` **%message%**'
  UserOnlineStatusUpdate:
    ONLINE:
      MinecraftFormat: '&6[&9Discord&6] &f%name%: is now &2%message%*'
      DiscordFormat: '``Time:`` **%time%** ``User:`` **%name%** ``Status:`` **%message%**'
    IDLE:
      MinecraftFormat: '&6[&9Discord&6] &f%name%: is now &6%message%*'
      DiscordFormat: '``Time:`` **%time%** ``User:`` **%name%** ``Status:`` **%message%**'
    DO_NOT_DISTURB:
      MinecraftFormat: '&6[&9Discord&6] &f%name%: is now &9%message%*'
      DiscordFormat: '``Time:`` **%time%** ``User:`` **%name%** ``Status:`` **%message%**'
    OFFLINE:
      MinecraftFormat: '&6[&9Discord&6] &f%name%: is now &9%message%*'
      DiscordFormat: '``Time:`` **%time%** ``User:`` **%name%** ``Status:`` **%message%**'
  VoiceDeafen:
    Deafened:
      MinecraftFormat: '&6[&9Discord&6] &f%name%: has been &9%message%*'
      DiscordFormat: '``Time:`` **%time%** ``User:`` **%name%** ``Voice:`` **%message%**'
    Undeafened:
      MinecraftFormat: '&6[&9Discord&6] &f%name%: has been &2%message%*'
      DiscordFormat: '``Time:`` **%time%** ``User:`` **%name%** ``Voice:`` **%message%**'
  VoiceMute:
    Muted:
      MinecraftFormat: '&6[&9Discord&6] &f%name%: has been &9%message%*'
      DiscordFormat: '``Time:`` **%time%** ``User:`` **%name%** ``Voice:`` **%message%**'
    Unmuted:
      MinecraftFormat: '&6[&9Discord&6] &f%name%: has been &2%message%*'
      DiscordFormat: '``Time:`` **%time%** ``User:`` **%name%** ``Voice:`` **%message%**'
  Player:
    Join:
      MinecraftFormat: 'null'
      DiscordFormat: '***> %name% %message%***'
    Death:
      MinecraftFormat: 'null'
      DiscordFormat: '***%name% %message%***'
      DiscordFormat: '``Time:`` **%time%** ``Server:`` **%server%** ``User:`` **%name%:** %message%'
    Quit:
      MinecraftFormat: 'null'
      DiscordFormat: '***< %name% %message%***'
  Channel:
    Global:
      MinecraftFormat: '&6[&9Discord&6] &6[&a%server%&6] &f%name%: %message%'
      DiscordFormat: '%server% **%name%** %message%'
  Command:
    List:
      MinecraftFormat: 'null'
      DiscordFormat: '```%command%```'
```

This configuration works with DiscordBot `build 6` doing minecraft > discord with no errors, but with that build there is a different error doing discord > minecraft (although nobody gets disconnected):
```
19:23:26 [SEVERE] Exception in thread "Thread-35" 
19:23:26 [SEVERE] java.lang.NullPointerException
19:23:26 [SEVERE]     at io.github.lxgaming.discordbot.util.MessageSender.getMinecraftFormat(MessageSender.java:104)
19:23:26 [SEVERE]     at io.github.lxgaming.discordbot.util.MessageSender.sendMessageMinecraft(MessageSender.java:69)
19:23:26 [SEVERE]     at io.github.lxgaming.discordbot.util.MessageSender$1.run(MessageSender.java:41)
19:23:26 [SEVERE]     at java.lang.Thread.run(Thread.java:745)
```
